#!/bin/bash

#	Y T W
#	o u a
#	u b t
#	  e c
#	    h

#	An extremely minimalistic youtube player.

#	${1}	Youtube URL
#	${2}	Video format
#		Values:
#		5	240p FLV
#		36	240p 3GP
#		83	240p MP4
#		More	http://en.wikipedia.org/wiki/YouTube#Quality_and_codecs

#	Dependencies:
#		youtube-dl
#		mplayer

#	Please modify the following varialbles to fit your needs:

#		Where you want your videos to be saved (this is the PWD by default):

			DOWNLOAD_DIR=`pwd`

#		How many seconds you wish to wait since the time you begin to download the
#		video, to the moment it starts playing. This gives youtube-dl time to
#		buffer the video. Consider your internet connection's speed, and just
#		use common sense (or trial and error) here:

			BUFF_DELAY=20

#

cd "${DOWNLOAD_DIR}"
FILENAME=`echo ${1} | sed 's/.*=//'`
youtube-dl --no-progress -t --restrict-filenames -f ${2} ${1} &
ls -- *${FILENAME}*
while test -z `ls *${FILENAME}* 2>/dev/null` ; do
	:
done
echo Please wait ${BUFF_DELAY} seconds
echo '(for your video to buffer)'
date
sleep ${BUFF_DELAY}
date
echo Playing...
ls -alh -- *${FILENAME}*
mplayer -hardframedrop -fs -lavdopts skipframe=noref:skiploopfilter=all -- *${FILENAME}*
rm -vi *${FILENAME}*
while test ${?} -ne 0 -a -e *${FILENAME}* ; do
	rm -vi *${FILENAME}*
done
